import type { Recipe } from "@/types/recipe"

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Creamy Mushroom Risotto",
    description:
      "A rich and creamy Italian risotto made with wild mushrooms, parmesan cheese, and fresh herbs. Perfect comfort food for any occasion.",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "italian",
    category: "dinner",
    cookTime: 35,
    servings: 4,
    difficulty: "medium",
    rating: 4.8,
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      { name: "Arborio rice", amount: "1.5", unit: "cups" },
      { name: "Mixed mushrooms", amount: "8", unit: "oz" },
      { name: "Vegetable broth", amount: "4", unit: "cups" },
      { name: "Parmesan cheese", amount: "1", unit: "cup" },
      { name: "White wine", amount: "1/2", unit: "cup" },
      { name: "Onion", amount: "1", unit: "medium" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Butter", amount: "3", unit: "tbsp" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    instructions: [
      "Heat the vegetable broth in a saucepan and keep it warm over low heat.",
      "In a large pan, heat olive oil and 1 tbsp butter. Sauté sliced mushrooms until golden.",
      "Remove mushrooms and set aside. In the same pan, sauté diced onion until translucent.",
      "Add minced garlic and cook for 1 minute. Add rice and stir for 2 minutes until lightly toasted.",
      "Pour in white wine and stir until absorbed. Begin adding warm broth one ladle at a time.",
      "Stir constantly and wait for each addition to be absorbed before adding more broth.",
      "Continue for 18-20 minutes until rice is creamy and al dente.",
      "Stir in cooked mushrooms, remaining butter, and grated Parmesan cheese.",
      "Season with salt and pepper. Serve immediately with extra Parmesan.",
    ],
    nutrition: {
      calories: 380,
      protein: 12,
      carbs: 58,
      fat: 14,
    },
  },
  {
    id: "2",
    title: "Spicy Thai Basil Chicken",
    description:
      "Authentic Thai stir-fry with ground chicken, holy basil, and chilies. Served over jasmine rice with a fried egg on top.",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "thai",
    category: "dinner",
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    rating: 4.6,
    dietary: ["gluten-free", "dairy-free"],
    ingredients: [
      { name: "Ground chicken", amount: "1", unit: "lb" },
      { name: "Thai basil leaves", amount: "1", unit: "cup" },
      { name: "Thai chilies", amount: "3-5", unit: "pieces" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Soy sauce", amount: "1", unit: "tbsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp" },
      { name: "Jasmine rice", amount: "2", unit: "cups cooked" },
    ],
    instructions: [
      "Heat oil in a wok or large skillet over high heat.",
      "Add minced garlic and sliced chilies, stir-fry for 30 seconds.",
      "Add ground chicken and break it up with a spatula.",
      "Cook chicken until no longer pink, about 5-7 minutes.",
      "Add fish sauce, soy sauce, and sugar. Stir to combine.",
      "Add Thai basil leaves and stir until wilted.",
      "Serve over jasmine rice with fried eggs if desired.",
      "Garnish with extra basil leaves and sliced chilies.",
    ],
    nutrition: {
      calories: 420,
      protein: 35,
      carbs: 45,
      fat: 12,
    },
  },
  {
    id: "3",
    title: "Mediterranean Quinoa Bowl",
    description:
      "Healthy and colorful bowl with quinoa, roasted vegetables, feta cheese, and tahini dressing. Perfect for meal prep!",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "mediterranean",
    category: "lunch",
    cookTime: 25,
    servings: 3,
    difficulty: "easy",
    rating: 4.7,
    dietary: ["vegetarian", "gluten-free", "high-protein"],
    ingredients: [
      { name: "Quinoa", amount: "1", unit: "cup" },
      { name: "Cherry tomatoes", amount: "1", unit: "cup" },
      { name: "Cucumber", amount: "1", unit: "large" },
      { name: "Red bell pepper", amount: "1", unit: "medium" },
      { name: "Red onion", amount: "1/4", unit: "cup" },
      { name: "Feta cheese", amount: "1/2", unit: "cup" },
      { name: "Kalamata olives", amount: "1/4", unit: "cup" },
      { name: "Tahini", amount: "3", unit: "tbsp" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
    ],
    instructions: [
      "Cook quinoa according to package directions and let cool.",
      "Dice cucumber, bell pepper, and red onion.",
      "Halve cherry tomatoes and crumble feta cheese.",
      "Make dressing by whisking tahini, lemon juice, and 2-3 tbsp water.",
      "Combine quinoa with all vegetables in a large bowl.",
      "Add feta cheese and olives.",
      "Drizzle with tahini dressing and toss gently.",
      "Serve chilled or at room temperature.",
    ],
    nutrition: {
      calories: 340,
      protein: 14,
      carbs: 42,
      fat: 16,
    },
  },
  {
    id: "4",
    title: "Classic Beef Tacos",
    description:
      "Traditional Mexican street tacos with seasoned ground beef, fresh toppings, and homemade salsa verde.",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "mexican",
    category: "dinner",
    cookTime: 30,
    servings: 4,
    difficulty: "easy",
    rating: 4.5,
    dietary: ["gluten-free", "dairy-free"],
    ingredients: [
      { name: "Ground beef", amount: "1", unit: "lb" },
      { name: "Corn tortillas", amount: "12", unit: "small" },
      { name: "White onion", amount: "1", unit: "medium" },
      { name: "Cilantro", amount: "1/2", unit: "cup" },
      { name: "Lime", amount: "2", unit: "limes" },
      { name: "Chili powder", amount: "2", unit: "tsp" },
      { name: "Cumin", amount: "1", unit: "tsp" },
      { name: "Paprika", amount: "1", unit: "tsp" },
      { name: "Salsa verde", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Heat a large skillet over medium-high heat.",
      "Add ground beef and cook, breaking it up as it browns.",
      "Season with chili powder, cumin, paprika, salt, and pepper.",
      "Cook until beef is fully browned and seasoned, about 8 minutes.",
      "Warm tortillas in a dry skillet or over an open flame.",
      "Dice onion and chop cilantro for toppings.",
      "Fill tortillas with seasoned beef.",
      "Top with diced onion, cilantro, and salsa verde.",
      "Serve with lime wedges on the side.",
    ],
    nutrition: {
      calories: 320,
      protein: 22,
      carbs: 28,
      fat: 14,
    },
  },
  {
    id: "5",
    title: "Blueberry Pancakes",
    description: "Fluffy buttermilk pancakes loaded with fresh blueberries. Perfect weekend breakfast treat!",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "american",
    category: "breakfast",
    cookTime: 20,
    servings: 4,
    difficulty: "easy",
    rating: 4.9,
    dietary: ["vegetarian"],
    ingredients: [
      { name: "All-purpose flour", amount: "2", unit: "cups" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Baking powder", amount: "2", unit: "tsp" },
      { name: "Salt", amount: "1/2", unit: "tsp" },
      { name: "Buttermilk", amount: "1.5", unit: "cups" },
      { name: "Eggs", amount: "2", unit: "large" },
      { name: "Butter", amount: "4", unit: "tbsp melted" },
      { name: "Fresh blueberries", amount: "1", unit: "cup" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
    ],
    instructions: [
      "In a large bowl, whisk together flour, sugar, baking powder, and salt.",
      "In another bowl, whisk buttermilk, eggs, melted butter, and vanilla.",
      "Pour wet ingredients into dry ingredients and stir until just combined.",
      "Gently fold in fresh blueberries.",
      "Heat a griddle or large skillet over medium heat.",
      "Pour 1/4 cup batter for each pancake onto the griddle.",
      "Cook until bubbles form on surface, then flip and cook until golden.",
      "Serve hot with butter and maple syrup.",
    ],
    nutrition: {
      calories: 280,
      protein: 8,
      carbs: 45,
      fat: 8,
    },
  },
  {
    id: "6",
    title: "Vegan Buddha Bowl",
    description: "Nourishing bowl with roasted vegetables, quinoa, chickpeas, and creamy avocado tahini dressing.",
    image: "/placeholder.svg?height=300&width=400",
    cuisine: "healthy",
    category: "lunch",
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    rating: 4.6,
    dietary: ["vegan", "gluten-free", "high-protein"],
    ingredients: [
      { name: "Quinoa", amount: "1", unit: "cup" },
      { name: "Sweet potato", amount: "1", unit: "large" },
      { name: "Broccoli", amount: "2", unit: "cups" },
      { name: "Chickpeas", amount: "1", unit: "can" },
      { name: "Avocado", amount: "1", unit: "ripe" },
      { name: "Red cabbage", amount: "1", unit: "cup shredded" },
      { name: "Tahini", amount: "3", unit: "tbsp" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Maple syrup", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Cook quinoa according to package directions.",
      "Cube sweet potato and toss with olive oil, salt, and pepper.",
      "Roast sweet potato for 25-30 minutes until tender.",
      "Steam broccoli until bright green and tender-crisp.",
      "Drain and rinse chickpeas, then roast for 15 minutes.",
      "Make dressing by whisking tahini, lemon juice, maple syrup, and water.",
      "Assemble bowls with quinoa, roasted vegetables, and chickpeas.",
      "Top with sliced avocado and shredded cabbage.",
      "Drizzle with tahini dressing before serving.",
    ],
    nutrition: {
      calories: 450,
      protein: 16,
      carbs: 65,
      fat: 18,
    },
  },
]

export const categories = [
  { id: "all", name: "All Recipes", icon: "🍽️", count: mockRecipes.length },
  {
    id: "breakfast",
    name: "Breakfast",
    icon: "🥞",
    count: mockRecipes.filter((r) => r.category === "breakfast").length,
  },
  { id: "lunch", name: "Lunch", icon: "🥗", count: mockRecipes.filter((r) => r.category === "lunch").length },
  { id: "dinner", name: "Dinner", icon: "🍝", count: mockRecipes.filter((r) => r.category === "dinner").length },
  { id: "dessert", name: "Dessert", icon: "🍰", count: mockRecipes.filter((r) => r.category === "dessert").length },
  { id: "snacks", name: "Snacks", icon: "🥨", count: mockRecipes.filter((r) => r.category === "snacks").length },
  {
    id: "beverages",
    name: "Beverages",
    icon: "🥤",
    count: mockRecipes.filter((r) => r.category === "beverages").length,
  },
]
